package com.github.orions29.ekspedisi.views;

import com.github.orions29.ekspedisi.controller.LoginController;
import com.github.orions29.ekspedisi.model.entity.User;

import javax.swing.*;

/**
 * Project: EkspedisiMasGiant
 * Package: com.github.orions29.ekspedisi.views
 * <p>
 * Panel Kurir dengan Radar Daftar Paket.
 * </p>
 *
 * <hr>
 * <table border="0">
 * <tr><td><b>Author</b></td><td>: Orions29</td></tr>
 * <tr><td><b>Date</b></td><td>: 30 June 2026</td></tr>
 * </table>
 * <hr>
 */
public class KurirViews extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KurirViews.class.getName());
    private User user;

    public KurirViews(User user) {
//        Error handling illegal akses ngelangkahi loginviews
        if (user == null) {
            throw new IllegalArgumentException("[Illegal Access] - Akses Illlegal, No No Login Dulu ya ");
        }
        this.user = user;
        initComponents();

//        Update Kurir Yang Logged IN
        jLabel3.setText(user.getUsername() + " (" + user.getId() + ")");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        logoutButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        resiPaketIn = new javax.swing.JTextField();
        submitPaket = new javax.swing.JButton();
        paketSelesaiButton = new javax.swing.JButton();

        cekPaketButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPaketArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel1.setText("Panel Operasional Kurir");

        jLabel2.setText("Petugas Kurir : ");
        jLabel3.setText("Username");

        logoutButton.setBackground(new java.awt.Color(204, 0, 51));
        logoutButton.setFont(new java.awt.Font("Segoe UI", 1, 12));
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Logout");
        logoutButton.setOpaque(true);
        logoutButton.setBorderPainted(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel4.setText("Scan Resi / Input Manual");

        resiPaketIn.setFont(new java.awt.Font("Consolas", 1, 14));

        submitPaket.setText("Bawa Paket");

        paketSelesaiButton.setBackground(new java.awt.Color(0, 153, 51));
        paketSelesaiButton.setFont(new java.awt.Font("Segoe UI", 1, 12));
        paketSelesaiButton.setForeground(new java.awt.Color(255, 255, 255));
        paketSelesaiButton.setText("Paket Diterima");
        paketSelesaiButton.setOpaque(true);
        paketSelesaiButton.setBorderPainted(false);

        cekPaketButton.setBackground(new java.awt.Color(255, 153, 0));
        cekPaketButton.setFont(new java.awt.Font("Segoe UI", 1, 12));
        cekPaketButton.setForeground(new java.awt.Color(0, 0, 0));
        cekPaketButton.setText("Cek Muatan Saya");
        cekPaketButton.setOpaque(true);
        cekPaketButton.setBorderPainted(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12));
        jLabel5.setText("Daftar Paket di Motor/Mobil:");

        listPaketArea.setEditable(false);
        listPaketArea.setBackground(new java.awt.Color(240, 240, 240));
        listPaketArea.setColumns(20);
        listPaketArea.setFont(new java.awt.Font("Consolas", 0, 12));
        listPaketArea.setRows(5);
        jScrollPane1.setViewportView(listPaketArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                                                .addComponent(logoutButton))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel3))
                                                        .addComponent(jLabel4)
                                                        .addComponent(resiPaketIn, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel5)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(submitPaket)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(paketSelesaiButton)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cekPaketButton)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(logoutButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resiPaketIn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(submitPaket, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(paketSelesaiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cekPaketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
    }


    public javax.swing.JButton getLogoutButton() {
        return logoutButton;
    }

    public javax.swing.JButton getSubmitPaket() {
        return submitPaket;
    }

    public javax.swing.JButton getPaketSelesaiButton() {
        return paketSelesaiButton;
    }

    public javax.swing.JButton getCekPaketButton() {
        return cekPaketButton;
    }

    public javax.swing.JTextField getResiPaketIn() {
        return resiPaketIn;
    }

    public javax.swing.JTextArea getListPaketArea() {
        return listPaketArea;
    }

    // Variables declaration
    private javax.swing.JButton cekPaketButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea listPaketArea;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton paketSelesaiButton;
    private javax.swing.JTextField resiPaketIn;
    private javax.swing.JButton submitPaket;
    // End of variables declaration
}