package com.github.orions29.ekspedisi.views;
import com.github.orions29.ekspedisi.controller.LoginController;
import com.github.orions29.ekspedisi.model.entity.User;

/**
 * Project: EkspedisiMasGiant
 * Package: com.github.orions29.ekspedisi.views
 * <p>
 * Panel Outlet (Loket) dengan Injeksi DNA User Absolut.
 * </p>
 *
 * <hr>
 * <table border="0">
 * <tr><td><b>Author</b></td><td>: Orions29</td></tr>
 * <tr><td><b>Date</b></td><td>: 30 May 2026</td></tr>
 * </table>
 * <hr>
 *
 * @author Orions29
 * @since 1.1
 */
public class OutletViews extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OutletViews.class.getName());

    // Kapsul identitas mutlak dari loket yang berhasil login
    private User loggedInUser;

    /**
     * Constructor wajib menerima lemparan data User!
     */
    public OutletViews(User user) {
        if (user == null) {
            throw new IllegalArgumentException("Fatal: Akses ilegal! Jendela loket wajib menerima data User yang valid.");
        }
        this.loggedInUser = user;

        initComponents();

        // 🚀 INJEKSI DATA KE UI (Bukan Hardcode Lagi!)
        jLabel3.setText(loggedInUser.getUsername() + " (" + loggedInUser.getId() + ")");
        jLabel1.setText("Panel Outlet Ekspedisi - " + (loggedInUser.getLocation() != null ? loggedInUser.getLocation() : "Pusat"));

        // Penyesuaian JSpinner agar mendukung format desimal (Double) sesuai ERD decimal(8,2)
        beratInput.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 99999.99d, 0.5d));
        volumeInput.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 99999.99d, 1.0d));

        // 🚀 THE FLAT DESIGN HACK (Memaksa warna solid)
        inputPaketButton.setBackground(new java.awt.Color(0, 102, 153));
        inputPaketButton.setForeground(new java.awt.Color(255, 255, 255));
        inputPaketButton.setOpaque(true);
        inputPaketButton.setContentAreaFilled(true);
        inputPaketButton.setBorderPainted(false);

        logoutButton.setBackground(new java.awt.Color(153, 0, 51));
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setOpaque(true);
        logoutButton.setContentAreaFilled(true);
        logoutButton.setBorderPainted(false);
    }

    private void logoutButtonActionPerformed(
            java.awt.event.ActionEvent evt
    ) {

        javax.swing.JFrame frame =
                new javax.swing.JFrame(
                        "EMG Tracking System - Login"
                );

        LoginView loginView =
                new LoginView();

        new LoginController(loginView);

        frame.setContentPane(loginView);

        frame.setDefaultCloseOperation(
                javax.swing.JFrame.EXIT_ON_CLOSE
        );

        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);

        this.dispose();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        panelInputPaket = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tipePaketInput = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        volumeInput = new javax.swing.JSpinner();
        beratInput = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        inputPaketButton = new javax.swing.JButton();
        panelInputIdentitas = new javax.swing.JPanel();
        namaPenerimaInput = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        destinasiPaketInput = new javax.swing.JTextField();
        labelNamaPenerima = new javax.swing.JLabel();
        labelDestinasiPaket = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatTujuanInput = new javax.swing.JTextArea();
        labelAlamatTujuan = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        labelNamaPengirim = new javax.swing.JLabel();
        namaPengirimInput = new javax.swing.JTextField();
        kotaPengirimInput = new javax.swing.JTextField();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Panel Outlet Ekspedisi (Loket)");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Petugas :");

        jLabel3.setText("Username_Loket");

        logoutButton.setText("Logout");
        logoutButton.addActionListener(this::logoutButtonActionPerformed);

        panelInputPaket.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Data Paket");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Berat (Kg)");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Volume (Cm3)");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Tipe Paket");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Estimasi Harga (Rp)");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Rp");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("0,00");

        inputPaketButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inputPaketButton.setText("Simpan Data Paket");
        inputPaketButton.addActionListener(this::inputPaketButtonActionPerformed);

        javax.swing.GroupLayout panelInputPaketLayout = new javax.swing.GroupLayout(panelInputPaket);
        panelInputPaket.setLayout(panelInputPaketLayout);
        panelInputPaketLayout.setHorizontalGroup(
                panelInputPaketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelInputPaketLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelInputPaketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelInputPaketLayout.createSequentialGroup()
                                                .addGroup(panelInputPaketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(panelInputPaketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(jLabel10)
                                                                .addComponent(jLabel14)
                                                                .addComponent(jLabel12)
                                                                .addComponent(tipePaketInput)
                                                                .addComponent(jLabel11)
                                                                .addComponent(volumeInput)
                                                                .addComponent(beratInput, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jLabel15)
                                                        .addGroup(panelInputPaketLayout.createSequentialGroup()
                                                                .addComponent(jLabel16)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel17)))
                                                .addGap(0, 22, Short.MAX_VALUE))
                                        .addComponent(inputPaketButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        panelInputPaketLayout.setVerticalGroup(
                panelInputPaketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelInputPaketLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tipePaketInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(volumeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(beratInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelInputPaketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(inputPaketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
        );

        panelInputIdentitas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Kota Pengirim");

        labelNamaPenerima.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNamaPenerima.setText("Nama Penerima");

        labelDestinasiPaket.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDestinasiPaket.setText("Destinasi Paket (Kota)");

        alamatTujuanInput.setColumns(20);
        alamatTujuanInput.setRows(5);
        jScrollPane1.setViewportView(alamatTujuanInput);

        labelAlamatTujuan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelAlamatTujuan.setText("Alamat Detail Tujuan");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Identitas dan Alamat");

        labelNamaPengirim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNamaPengirim.setText("Nama Pengirim");

        javax.swing.GroupLayout panelInputIdentitasLayout = new javax.swing.GroupLayout(panelInputIdentitas);
        panelInputIdentitas.setLayout(panelInputIdentitasLayout);
        panelInputIdentitasLayout.setHorizontalGroup(
                panelInputIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelInputIdentitasLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelInputIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addGroup(panelInputIdentitasLayout.createSequentialGroup()
                                                .addGroup(panelInputIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(labelNamaPengirim)
                                                        .addComponent(jLabel6)
                                                        .addComponent(namaPengirimInput)
                                                        .addComponent(kotaPengirimInput, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                                                .addGap(57, 57, 57)
                                                .addGroup(panelInputIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(panelInputIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(labelDestinasiPaket)
                                                                .addComponent(labelNamaPenerima)
                                                                .addComponent(labelAlamatTujuan)
                                                                .addComponent(namaPenerimaInput)
                                                                .addComponent(destinasiPaketInput, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(30, Short.MAX_VALUE))
        );
        panelInputIdentitasLayout.setVerticalGroup(
                panelInputIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelInputIdentitasLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelInputIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelNamaPengirim)
                                        .addComponent(labelNamaPenerima))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelInputIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(namaPengirimInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(namaPenerimaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelInputIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelDestinasiPaket)
                                        .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelInputIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(destinasiPaketInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(kotaPengirimInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelAlamatTujuan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator2)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(logoutButton))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(panelInputIdentitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(panelInputPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 24, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(logoutButton))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(panelInputPaket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(panelInputIdentitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>

    private void btnLogoutActionPerformed(
            java.awt.event.ActionEvent evt
    ) {

        javax.swing.JFrame frame =
                new javax.swing.JFrame(
                        "EMG Tracking System - Login"
                );

        LoginView loginView =
                new LoginView();

        new LoginController(loginView);

        frame.setContentPane(loginView);

        frame.setDefaultCloseOperation(
                javax.swing.JFrame.EXIT_ON_CLOSE
        );

        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);

        this.dispose();
    }

    private void inputPaketButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String senderName = namaPengirimInput.getText().trim();
        String originCity = kotaPengirimInput.getText().trim();
        String receiverName = namaPenerimaInput.getText().trim();
        String destinationCity = destinasiPaketInput.getText().trim();
        String destinationAddress = alamatTujuanInput.getText().trim();
        String typePaket = tipePaketInput.getText().trim();

        double weight = (Double) beratInput.getValue();
        double volume = (Double) volumeInput.getValue();


        /* TODO: PANGGIL PAKET DAO & TRACKING DAO DI SINI
           1. Generate Resi via GeneratorUtil
           2. Bikin Entity Paket dan lempar ke paketDao.insertPaket()
           3. AMBIL LOKASI ABSOLUT DARI loggedInUser.getLocation() 👈
           4. Bikin Entity ShipmentLog (Status "Diterima di Loket") dan lempar ke trackingDao.insertLog()
        */

        String pesanSukses = String.format("Data Paket berhasil disiapkan untuk dikirim ke database!\n\n"
                        + "Pengirim: %s (%s)\n"
                        + "Penerima: %s (%s)\n"
                        + "Berat: %.2f kg\n"
                        + "Volume: %.2f cm3\n"
                        + "Tipe: %s\n\n"
                        + "📍 Lokasi Input: %s",
                senderName, originCity, receiverName, destinationCity, weight, volume, typePaket, loggedInUser.getLocation());

        javax.swing.JOptionPane.showMessageDialog(this, pesanSukses, "Sukses Menyimpan Data", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

    // ⚠️ main() ini diubah HANYA untuk ngetes UI secara mandiri.
    public static void main(String[] args) {
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                // Simulasi Dummy User agar form tetap bisa dites lewat psvm
                User dummyUser = new User("L-1001", "loket_rani", "hash", "loket", "Loket Pusat Godean");
                OutletViews frame = new OutletViews(dummyUser);
                frame.setTitle("EMG Tracking System - Outlet");
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }

    public javax.swing.JButton getInputPaketButton() {
        return inputPaketButton;
    }

    public javax.swing.JTextField getNamaPengirimInput() {
        return namaPengirimInput;
    }

    public javax.swing.JTextField getNamaPenerimaInput() {
        return namaPenerimaInput;
    }

    public javax.swing.JTextField getDestinasiPaketInput() {
        return destinasiPaketInput;
    }

    public javax.swing.JTextArea getAlamatTujuanInput() {
        return alamatTujuanInput;
    }

    public javax.swing.JTextField getTipePaketInput() {
        return tipePaketInput;
    }

    public javax.swing.JSpinner getBeratInput() {
        return beratInput;
    }

    public javax.swing.JSpinner getVolumeInput() {
        return volumeInput;
    }

    // Variables declaration - do not modify
    private javax.swing.JTextArea alamatTujuanInput;
    private javax.swing.JSpinner beratInput;
    private javax.swing.JTextField destinasiPaketInput;
    private javax.swing.JButton inputPaketButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField kotaPengirimInput;
    private javax.swing.JLabel labelAlamatTujuan;
    private javax.swing.JLabel labelDestinasiPaket;
    private javax.swing.JLabel labelNamaPenerima;
    private javax.swing.JLabel labelNamaPengirim;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTextField namaPenerimaInput;
    private javax.swing.JTextField namaPengirimInput;
    private javax.swing.JPanel panelInputIdentitas;
    private javax.swing.JPanel panelInputPaket;
    private javax.swing.JTextField tipePaketInput;
    private javax.swing.JSpinner volumeInput;
    // End of variables declaration

}